# 遊戲配置文件
game:
  # 遊戲基本設置
  default_players: 4 # 默認玩家數量
  default_human_player: 0 # 默認人類玩家編號

  # 遊戲規則
  cards_per_type: 6 # 每種牌的數量
  jokers: 2 # Joker牌的數量
  max_cards_play: 3 # 每次最多可以出的牌
  max_gun_positions: 6 # 手槍最大轉輪位置

  # 顯示設置
  debug: false # 是否啟用調試模式
  show_intro: true # 是否顯示遊戲介紹

  # 日誌設置
  log_level: "info" # 日誌級別: debug, info, warning, error
  log_to_file: true # 是否記錄到文件
  log_file_path: "game_logs" # 日誌文件路徑
